-- =========================================================
-- 0016 — Admin portal redesign: unique display ID + source
--
-- (1) epc_business.epc_display_id text UNIQUE
--     Format:  CC-<mobile-last-5>-<5-digit-sequence>
--     Example: CC-07608-00042
--     Generated by a BEFORE INSERT trigger. Legacy rows are backfilled
--     below in created_at order (oldest = 00001).
--     FROZEN AT CREATION — never regenerated. If the mobile is later
--     edited (self-edit or admin), the display_id keeps its original
--     mobile-last-5 fragment. This is intentional: the display_id is a
--     stable identifier of the EPC record, not of their current mobile.
--
-- (2) epc_business.source text default 'website'
--     'website' = self-onboarded via the wizard
--     'manual'  = admin-created via the Add New EPC flow
--     Legacy rows default to 'website' automatically via the column default.
--
-- (3) Sequence epc_display_seq — nextval-driven; never uses count()
--     so concurrent inserts cannot collide. Advanced past the backfill
--     max at the end of this migration.
--
-- Rollback:
--   drop trigger if exists trg_epc_business_display_id on epc_business;
--   drop function if exists epc_business_assign_display_id();
--   drop function if exists epc_format_display_id(text, bigint);
--   drop function if exists epc_display_last5(text);
--   alter table epc_business drop column if exists epc_display_id;
--   alter table epc_business drop column if exists source;
--   drop sequence if exists epc_display_seq;
-- =========================================================

create sequence if not exists epc_display_seq start with 1;

alter table epc_business
  add column if not exists epc_display_id text unique;

alter table epc_business
  add column if not exists source text not null default 'website';

-- ── Helpers ─────────────────────────────────────────────────
-- Last 5 chars of the mobile after stripping non-digits, left-padded
-- with zeros if shorter than 5. Handles null/empty gracefully → "00000".
create or replace function epc_display_last5(mobile text) returns text as $$
  select lpad(coalesce(right(regexp_replace(coalesce(mobile,''), '\D', '', 'g'), 5), ''), 5, '0');
$$ language sql immutable;

create or replace function epc_format_display_id(mobile text, seq bigint) returns text as $$
  select 'CC-' || epc_display_last5(mobile) || '-' || lpad(seq::text, 5, '0');
$$ language sql immutable;

-- ── Trigger ─────────────────────────────────────────────────
-- Fires on INSERT only. On UPDATE the display_id is NEVER regenerated —
-- the ID is frozen at creation. If display_id is already provided (e.g.
-- explicitly passed by an import script) the trigger leaves it alone.
create or replace function epc_business_assign_display_id() returns trigger as $$
begin
  if new.epc_display_id is null then
    new.epc_display_id := epc_format_display_id(new.contact_mobile, nextval('epc_display_seq'));
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_epc_business_display_id on epc_business;
create trigger trg_epc_business_display_id
  before insert on epc_business
  for each row execute function epc_business_assign_display_id();

-- ── Backfill legacy rows ────────────────────────────────────
-- Assigns sequence numbers by created_at ASC so the oldest EPC becomes
-- 00001, the next 00002, and so on. After the update, we advance the
-- sequence past the highest used number so new inserts never collide
-- with a backfilled ID.
do $$
declare
  max_seq bigint;
begin
  with ordered as (
    select id,
           contact_mobile,
           row_number() over (order by created_at asc, id asc) as rn
      from epc_business
     where epc_display_id is null
  )
  update epc_business b
     set epc_display_id = epc_format_display_id(b.contact_mobile, o.rn)
    from ordered o
   where b.id = o.id;

  select coalesce(max(nullif(regexp_replace(epc_display_id, '.*-', ''), '')::bigint), 0)
    into max_seq
    from epc_business
   where epc_display_id is not null;

  -- setval(seq, N, true) → next nextval() returns N+1. Guarantees new
  -- inserts get the next unused number, no collision with the backfill.
  perform setval('epc_display_seq', greatest(max_seq, 1), true);
end$$;
